qr_data:
  - "https://netdron.es/survey/234234"
  - "https://netdron.es/survey/908098"
  - "https://netdron.es/survey/68763"
  - "ipfs://QmZSTrVzb4U9jZ1BzvM9PZGu8jmUGXoMDJTZWcFSxPUvy2"
search:
  - ./images/IMG_2884.png
  - ./images/IMG_2895.png
  - ./images/IMG_2896.png
  - ./images/IMG_2897.png
  - ./images/IMG_2898.png
  - ./images/IMG_2899.png
  - ./images/IMG_2900.png
  - ./images/IMG_2901.png
  - ./images/IMG_2902.png
  - ./images/IMG_2903.png
  - ./images/IMG_2904.png
