---
# requires python 3.2 or higher
# https://gist.github.com/kingspp/9451566a5555fb022215ca2b7b802f19
# https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
version: 1
formatters:
  standard:
    format: "%(levelname)-8s [%(filename)s:%(lineno)d] $(funcName)s: %(message)s"
  detailed:
    format: "%(asctime)s %(levelname)-8s [%(name)s:%(filename)s:%(lineno)d %(funcName)s] %(message)s"
    datefmt: "%Y-%m-%d:%H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: CRITICAL
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: detail.log
    maxBytes: 10485760  # 10 MB
    backupCount: 20
    encoding: utf8

loggers:
  # the default entry point into a python program
  __main__:
    level: DEBUG
    handlers: [console, file]
    # https://docs.python.org/3/library/logging.html
    # propagate means send the event to all ancestors
    # in addition to all handlers attached to current logger
    # if you attach handlers only to the top level then
    # it will coalesce all children messages
    propagate: yes  # yamllint disable-line
  # each library gets its own logger
  netqr:
    level: DEBUG
    handlers: [console, file]
    propagate: yes  # yamllint disable-line

# if no name is specified in log=logging.getLogger(),
# there is a default logger called root
root:
  level: DEBUG
  handlers: [console, file]
  propagate: yes  # yamllint disable-line
